# Notes:
#
# Tests for linux and osx are run together on travis
#
# py37 requires dist xenial to run on linux: 
# 	https://docs.travis-ci.com/user/languages/python/#python-37-and-higher
#
# osx requires language generic, and only py27 and py36 are supported
#	https://docs.travis-ci.com/user/multi-os/#python-example-unsupported-languages

sudo: false
language: python
os: linux

matrix:
  include:
    - python: 3.6
      env:
        - TOXENV=check
    - python: 3.5
      env:
        - TOXENV=py35
    - python: 3.6
      env:
        - TOXENV=py36
    - python: 3.7
      dist: xenial
      env:
        - TOXENV=py37
    - os: osx
      language: generic
      env:
        - TOXENV=py36
before_install:
  - python --version
  - uname -a
install:
  - pip install tox
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version
script:
  - tox
