# Notes:
#
# Tests for linux and osx are run together on travis
#
# py37 requires dist xenial to run on linux: 
# 	https://docs.travis-ci.com/user/languages/python/#python-37-and-higher
#
# osx requires a hackish approach to run specific versions of Python:
#   https://blog.travis-ci.com/2019-08-07-extensive-python-testing-on-travis-ci

sudo: false
language: python
os: linux
dist: xenial

matrix:
  include:
    - python: 3.7
      env:
        - TOXENV=check
    - python: 3.7
      env:
        - TOXENV=coverage
      after_success:
        - pip install codecov
        - codecov
    - python: 3.7
      env:
        - TOXENV=docs
    - python: 3.6
      env:
        - TOXENV=py36
    - python: 3.7
      env:
        - TOXENV=py37
    - python: 3.8
      dist: bionic
      env:
        - TOXENV=py38
    - os: osx
      osx_image: xcode10.2 # xcode10.2 — Comes pre-installed with Python 3.7.3
      language: shell  # 'language: python' is an error on Travis CI macOS
      env:
        - TOXENV=py37
      install:
        - python3 --version
        - python3 -m pip install tox
        - tox --version
before_install:
  - python --version
  - uname -a
install:
  - pip install tox
  - virtualenv --version
  - pip --version
  - tox --version
script:
  - tox
